version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8089:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - netgear

  php:
    build: ./php/.
    working_dir: /var/www/html
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=1024M
    networks:
      - netgear

  mariadb:
    image: mariadb:10.5
    restart: always
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: UrXc3whE2q2U5MZfnet
      MYSQL_DATABASE: gear
    volumes:
      - ./db/:/var/lib/mysql/
    networks:
      - netgear
 
  adminer:
    image: michalhosna/adminer
    restart: always
    ports:
      - 8079:8080
    environment:
      ADMINER_PASSWORD: UrXc3whE2q2U5MZfnet
      ADMINER_SERVER: mariadb
      ADMINER_USERNAME: root
    networks:
      - netgear

networks:
  netgear: